# Generated by Django 5.0.6 on 2024-05-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_product_farmer_product_category_and_more'),
    ]

    operations = [
    ]
